name: my_meals_app
description: "An app to track your meals and rate them."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  url_launcher: ^6.2.6
  sqflite: ^2.3.3
  path: ^1.9.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  meta: ^1.11.0
  shared_preferences: ^2.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"
  web:
    generate: true
    image_path: "assets/images/launcher_icon.png"

